add WebsocketErrInstanceNotExists for websocket disconnection
go-chassis/cari pull request #39
Opened 2021-08-20 10:17 UTC by robotLJW

2021-08-20 10:35 UTC, tianxiaoliang approved these changes

2021-08-20 10:36 UTC, tianxiaoliang commented on discovery/error.go
> +	WebsocketErrInstanceNotExists int = 4001
风格与下边不同

2021-08-20 10:40 UTC, robotLJW commented on discovery/error.go
> +	WebsocketErrInstanceNotExists int = 4001
https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.2 是这样的自定义错误是int，而且有个范围

2021-08-23 01:42 UTC, little-cui requested changes

2021-08-23 01:42 UTC, little-cui commented on discovery/error.go
> +	WebsocketErrInstanceNotExists int = 4001
一般错误，都以ErrXX开头，便于IDE联想

2021-08-23 02:30 UTC, merged