[feat] add etcd and mongo db client
go-chassis/cari pull request #52
Opened 2022-01-13 11:28 UTC by robotLJW

2022-01-13 13:12 UTC, little-cui requested changes

2022-01-13 13:12 UTC, little-cui commented on db/types.go
> +	DBName      string        `yaml:"dbName"`
1、cari行为：通过URI可以指定dbName，不指定时报错
2、使用cari库的组件：自行指定默认值，如：servicecomb

2022-01-13 14:28 UTC, little-cui approved these changes

2022-01-13 14:36 UTC, little-cui requested changes

2022-01-13 14:36 UTC, little-cui commented on db/etcd/etcd.go
> +	openlog.Info(fmt.Sprintf("use %s as storage", c.Kind))
怎么注入日志框架？

2022-01-14 03:00 UTC, robotLJW commented on db/etcd/etcd.go
> +	openlog.Info(fmt.Sprintf("use %s as storage", c.Kind))
已经修改

2022-01-14 09:42 UTC, little-cui requested changes

2022-01-14 09:42 UTC, little-cui commented on db/mongo/dlock.go
> +	return nil
TODO应该要返回错误

2022-01-14 09:43 UTC, little-cui requested changes

2022-01-14 09:43 UTC, little-cui commented on db/mongo/log/logger.go
> +var globalLogger = Logger{}
cari不做log具体实现，只做config配置，传入openlog.logger

2022-01-17 09:09 UTC, little-cui requested changes

2022-01-17 14:22 UTC, little-cui approved these changes

2022-01-17 14:36 UTC, merged